[package]
name = "january"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.6"
reqwest = "0.11.3"
scraper = "0.12.0"
serde = "1"